kind: pipeline
name: default

trigger:
  event:
    exclude:
      - pull_request

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - shellcheck --version
    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/radarr
    auto_tag: true

- name: microbadger
  image: plugins/webhook
  pull: always
  settings:
    urls:
      - https://hooks.microbadger.com/images/hotio/radarr/4yjTYSA2fogGjK-RKB-UxvS0QPc=
