#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ "${VERSION}" != "image" ]]; then
    if grep -qs "${APP_DIR}" /proc/mounts; then
        echo -e '\e[31m'"Incorrect mount detected! Aborting app installation for security reasons."'\e[0m'
        exit 1
    else
        case "${ARCH}" in
            linux-amd64)
                architecture="x64"
                ;;
            linux-arm64)
                architecture="arm64"
                ;;
            linux-arm)
                architecture="arm"
                ;;
        esac
        case "${VERSION}" in
            stable|unstable)
                radarr_version=$(curl -fsSL "https://radarr.lidarr.audio/v1/update/aphrodite/changes?os=linux" | jq -r '.[0].version')
                url="https://radarr.lidarr.audio/v1/update/aphrodite/updatefile?version=${radarr_version}&os=linux&runtime=netcore&arch=${architecture}"
                ;;
            *)
                url="${VERSION}"
                ;;
        esac
        rm -rf "${APP_DIR}" && mkdir "${APP_DIR}" && tempfile="$(mktemp)" && curl -fsSL -o "${tempfile}" "${url}" && tar xzf "${tempfile}" -C "${APP_DIR}" --strip-components=1 && chmod -R u=rwX,go=rX "${APP_DIR}" && rm -f "${tempfile}" && INSTALL_OK="yes"
        if [[ "${INSTALL_OK}" != "yes" ]]; then
            echo -e '\e[31m'"Installation of \"${url}\" failed!"'\e[0m'
            exit 1
        fi
    fi
fi
